stages:
  - build
  - deploy

build:
  stage: build
  image: python:3.8-alpine
  before_script:
    - pip install pytest
    - pip install -e .
  script:
    - pytest $(find -name "*_test.py")
  after_script:
    - python ./setup.py sdist bdist_wheel
  artifacts:
    paths:
      - dist/*
    expire_in: 1 week

deploy:
  stage: deploy
  image: python:3.8-buster
  rules:
    # Only execute deployment if we're on a release branch and have /release
    # in the commit message.
    - if: '$CI_COMMIT_TITLE =~ /^\/release/ && $CI_COMMIT_REF_NAME =~ /^v.*/'
  before_script:
    - pip install twine
  script:
    - twine check dist/*
    - twine upload dist/*